config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
root 'main#home'
post 'backend/login', to: 'backend#login', as: :backend_login
get 'backend/menu', to: 'backend#menu', as: :backend_menu
get 'backend/start', to: 'backend#start', as: :backend_start
get 'archive', to: 'main#archive', as: :archive
get 'backend/destroyarticle/:id', to: 'backend#destroyarticle', as: :destroy_article
post 'addemail', to: 'email#addemail', as: :addemail
resources :articles, except: [:index, :destroy], param: :abv_title
end

app/models/admin.rb
class Admin < ApplicationRecord
  has_secure_password
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
has_one_attached :display_pic
has_one_attached :pic1
has_one_attached :pic2
validates :display_pic, blob: { content_type: :image }
validates :display_pic, presence: true
validates :title, presence: true
validates :abv_title, presence: true, uniqueness: true
validates :paragraph1, presence: true
validates :paragraph2, presence: true
end

app/models/email.rb
class Email < ApplicationRecord
validates :emailstring, format: { with: URI::MailTo::EMAIL_REGEXP }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < LoginController
before_action :logdin, except: [:show]
before_action :find_article, only: [:show, :edit]

def new
@article = Article.new
render layout: "backend"
end
def create
@article = Article.create(article_params)
respond_to do |f|
if @article.save
	Email.all.each do |f|
	ArticleMailer.with(article: @article, address: f.emailstring).article_email.deliver!
	end
	f.html { redirect_to backend_menu_path }
else
	f.html { render 'new', layout: "backend" }
end
end
end
def edit
render layout: "backend"
end
def update
@article = Article.find(params[:abv_title])
respond_to do |f|
if @article.update(article_params)
	f.html { redirect_to backend_menu_path }
else
	f.html { render 'edit' }
end
end
end
def show

end


def find_article
@article = Article.find_by(abv_title: params[:abv_title])
end

private
def article_params
params.require(:article).permit(:title, :abv_title, :paragraph1, :paragraph2, :paragraph3, :paragraph4, :display_pic, :pic1, :pic2)
end
end

app/controllers/backend_controller.rb
class BackendController < LoginController
before_action :logdin, only: [:menu, :destroyarticle]

def menu
@articles = Article.all
end
def destroyarticle
@theid = params[:id].to_i
@article = Article.find(@theid)
@article.destroy
respond_to do |f|
	f.js
end
end

def login
admin = Admin.find_by(username: params[:user])
if admin && admin.authenticate(params[:pass])
session[:admin] = admin.username
redirect_to backend_menu_path
else
redirect_to backend_start_path
end
end
end

app/controllers/email_controller.rb
class EmailController < ApplicationController
def addemail
@emailstriing = ActionController::Base.helpers.sanitize(params[:emailstring])

unless Email.find_by(emailstring: @emailstriing).blank?
@theemail = Email.find_by(emailstring: params[:emailstring])
@theemail.destroy
render :deleteemail
else
@theemail = Email.create(emailstring: @emailstriing)
if @theemail.save
render :addemail
else
render :bademail
end
end
end

private
def email_params
params.require(:email).permit(:emailstring)
end
end

app/controllers/login_controller.rb
class LoginController < ApplicationController
def logdin
	if session[:admin].present?
	return true
	else
	redirect_to backend_start_path
end
end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
def home
@lastarticle = Article.last
@twoarticles = Article.order("id DESC").offset(1).first(2)
@fourarticles = Article.order("id DESC").offset(3).first(4)
@columnstop = 0
end
def archive
@articles = Article.all
end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/backend_helper.rb
module BackendHelper
end

app/helpers/email_helper.rb
module EmailHelper
end

app/helpers/login_helper.rb
module LoginHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/views/articles/_form.html.erb
<%= form_for @article do |f| %>

<% if @article.errors.any? %>
	<% @article.errors.full_messages.each do |msg| %>
	<%= msg %><br>
	<% end %>
<% end %>

<%= f.label :title, "Article title" %>
<%= f.text_field :title %><br><br>

<%= f.label :abv_title, "This will go in the article URL" %>
<%= f.text_field :abv_title %><br><br>

<%= f.label :paragraph1, "Paragraph 1" %>
<%= f.text_area :paragraph1 %><br><br>

<%= f.label :paragraph2, "Paragraph 2" %>
<%= f.text_area :paragraph2 %><br><br>

<%= f.label :paragraph3, "Paragraph 3" %>
<%= f.text_area :paragraph3 %><br><br>

<%= f.label :paragraph4, "Paragraph 4" %>
<%= f.text_area :paragraph4 %><br><br>

<%= f.label :display_pic, "The display picture" %>
<%= f.file_field :display_pic %><br><br>

<%= f.label :pic1, "Up to 2 pictures for the article" %>
<%= f.file_field :pic1 %><br><br>

<%= f.label :pic2, "Up to 2 pictures for the article" %>
<%= f.file_field :pic2 %>

<%= f.submit "Add article" %>

<% end %>

app/views/articles/edit.html.erb
<%= render partial: "form" %>

app/views/articles/new.html.erb
<%= render partial: "form" %>

app/views/articles/show.html.erb
<% @para1 = simple_format(@article.paragraph1) %>
<% @para2 = simple_format(@article.paragraph2) %>
<% @para3 = simple_format(@article.paragraph3) %>
<% @para4 = simple_format(@article.paragraph4) %>
<article id = "articlebox" itemscope itemtype="http://schema.org/Article">
<%= image_tag(@article.display_pic, id: "showdp", class: "showpic") %>

<h1 id = "title" itemprop="name"><%= @article.title %></h1>
<div itemprop="articleBody">
<section class = "articleparagraph">
<%= @para1 %>
</section>

<% if @article.pic1.attached? %>
<%= image_tag(@article.pic1, class: "showpic") %>
<% end %>

<section class = "articleparagraph">
<%= @para2 %>
</section>

<section class = "articleparagraph" %>
<%= @para3 %>
</section>

<% if @article.pic2.attached? %>
<%= image_tag(@article.pic2, class: "showpic") %>
<% end %>

<section class = "articleparagraph" %>
<%= @para4 %>
</section>
</div>
</article>

app/views/backend/destroyarticle.js.erb
var toRemove = document.getElementById("article-<%= @theid %>");
var theParent = toRemove.parentNode;
theParent.removeChild(toRemove);

app/views/backend/menu.html.erb
Hello World!<br>
<% @articles.each do |m| %>

<div id = "article-<%= m.id %>">
<%= link_to edit_article_path(m.abv_title) do %>
<%= m.title %>
<% end %>
	
<%= link_to destroy_article_path(m.id), remote: true do %>
<div class = "deletebutton">Delete</div>
<% end %>
<br>
</div>
<% end %>

app/views/backend/start.html.erb
<%= form_with url: backend_login_path do |f| %>
	<%= f.label :user, "Username: " %>
	<%= f.text_field :user %><br><br>
	<%= f.label :pass, "Password: " %>
	<%= f.password_field :pass %>
	<br><br><%= f.submit "Login" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Frodho Blog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
	<meta name="viewport" content="width=device-width, initial-scale=1">
  </head>

  <body>
	<header id = "titlebox"><%= link_to "Frodho Blog", root_path %></header>
	<main id = "contentbox">
    <%= yield %>
	</main>
	<div id = "bottom-box">
	<%= form_with url: addemail_path, method: :post, id: "addemailform" do |f| %>
	<%= f.label :email, "Be a part of our mailing list: " %>
	<%= f.text_field :emailstring, id: "addemailinput" %>
	<div id = "responsebox">Enter your email address to put it on our mailing list. Enter it again to take it off.</div>
	<% end %>
	</div>
	    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </body>
</html>

app/views/layouts/backend.html.erb
<!DOCTYPE html>
<html>
	<head>
	<title>Frodho Blog</title>
	<%= csrf_meta_tags %>
    <%= csp_meta_tag %>
	
	<%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
	</head>
	<body>
		<div id = "titlebox">Frodho Blog Backend</div>
		<%= yield %>
		<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
	</body>
</html>

app/views/main/_display_large.html.erb
<%= link_to article_path(display_large.abv_title) do %>
<div class = "story big">
<div class = "textbox"><%= display_large.title %></div>
<div class = "filler"></div>
<div class = "picbox"><%= image_tag(display_large.display_pic, class: "displaypic") %></div>
</div>
<% end %>

app/views/main/_display_medium.html.erb
<%= link_to article_path(display_medium.abv_title) do %>
<div class = "story medium">
<div class = "textbox"><%= display_medium.title %></div>
<div class = "filler"></div>
<div class = "picbox"><%= image_tag(display_medium.display_pic, class: "displaypic") %></div>
</div>
<% end %>

app/views/main/_display_small.html.erb
<%= link_to article_path(display_small.abv_title) do %>
<div class = "story small">
<%= display_small.title %>
</div>
<% end %>

app/views/main/archive.html.erb
Archive:
<ul>
<% @articles.each do |f| %>
<li><%= link_to article_path(f.abv_title) do %>
<%= f.title %>
<% end %>
</li>
<% end %>
</ul>

app/views/main/home.html.erb
<div id = "mainlayout">
<div id = "bigcolumn">

<% unless @lastarticle.blank? %>
<%= render partial: "main/display_large", object: @lastarticle %>
<% else %>
<div class = "story big">
<span class = "fillertext">Frodho Blog</span>
</div>
<% end %>
<div class = "fillerbar"></div>
<% unless @twoarticles[0].blank? %>
<%= render partial: "main/display_medium", object: @twoarticles[0] %>
<% else %>
<div class = "story medium">
<span class = "fillertext">Frodho Blog</span>
</div>
<% end %>
<div id = "divider"></div>
<% unless @twoarticles[1].blank? %>
<%= render partial: "main/display_medium", object: @twoarticles[1] %>
<% else %>
<div class = "story medium">
<span class = "fillertext">Frodho Blog</span>
</div>
<% end %>
</div>
<div id = "smallcolumn">
<% [0,1,2,3].each do |m| %>
<% unless @fourarticles[m].blank? %>
	<%= render partial: "main/display_small", object: @fourarticles[m] %>
<% else %>
	<div class = "story small">
	<span class = "fillertext">Frodho Blog</span>
	</div>
<% end %>
<% @columnstop += 1 %>
<% unless @columnstop == 4 %>
<div class = "smallcolfiller"></div>
<% end %>
<% end %>
</div>
</div>